### ISSUE TITLE
Dataset Download link not working

### ISSUE THREAD

**Issue by Muhammad-Zeerak-Khan** [Ashishkumar-hub/Warehouse-Apparel-Detection-using-YOLOv5#1]
The link provided in the dataset_downloader.py file isn't working. 
Kindly update the dataset link.

**Comment by Ashishkumar-hub** [comment]
Hi you can scrap some warehouse images from the net and label them for you model traning it is a very old project I did I had to clean my drive as it was getting full so I have deleted the dataset.
